Filiprogrammer/AlphabotSZUCar

- esp32/PrimaryESP32/alphabot/DistanceMeter.cpp
- esp32/PrimaryESP32/lib/Mecha_QMC5883L/src/MechaQMC5883.cpp
Fix compiler warnings by adding a 'U' suffix to unsigned integers.
> esp32/PrimaryESP32: Fix compiler warnings

- rpi/sd_image/build_in_container.sh
Use chrony instead of systemd-timesyncd as the NTP client to get the
current time.
> rpi/sd_image: Replace systemd-timesyncd with chrony

- rpi/sd_image/build_in_container.sh
Remove service/target waiting for the network to come online.
Closes #21
> rpi/sd_image: Remove service waiting to go online

- emulator_rpi.py
Fix colorama not displaying color when running the emulator in a GitHub
Actions workflow.
Closes #1
> emulator_rpi: Fix colorama color in GitHub Actions

- emulator_rpi.py
Avoid an error if the tkinter Python module is not installed when
starting the emulator in headless mode.
> emulator_rpi: Fix error when tkinter is missing

- docs/wifi_ble_communication_protocol.md
- Clarifies the "little-endian" standard which should be used
- Changed id in the "New obstacle registered" packet on WiFi to the end of the packet, for consistency reasons to the BLE packet
> docs: Update communication protocol

- esp32/PrimaryESP32/alphabot/Compass.cpp
- esp32/PrimaryESP32/alphabot/Compass.h
- esp32/PrimaryESP32/alphabot/DrivingAssistent.cpp
- esp32/PrimaryESP32/alphabot/DrivingAssistent.h
- esp32/PrimaryESP32/alphabot/Navigator.cpp
- esp32/PrimaryESP32/alphabot/Navigator.h
- esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
- esp32/PrimaryESP32/alphabot/PositioningSystem.h
- esp32/PrimaryESP32/alphabot/SaveFile.cpp
- esp32/PrimaryESP32/alphabot/SaveFile.h
- esp32/PrimaryESP32/alphabot/TwoMotorDrive.cpp
- esp32/PrimaryESP32/alphabot/TwoMotorDrive.h
Add the const keyword to class member functions that do not modify the
called object.
> esp32/PrimaryESP32: Make some member functions const

- docs/wifi_ble_communication_protocol.md
Add time stamps to BLE characteristics which should arrive in the
correct order and might be re-sent by the client if the server does not
respond within a specified time frame.
> docs: Add timestamps to BLE protocol specification

- esp32/PrimaryESP32/alphabot/BLEHandler.cpp
Advertise the BLE service UUID to improve support with other clients.
> esp32/PrimaryESP32: Expose BLE service

- esp32/PrimaryESP32/alphabot/Navigator.cpp
Fix Alphabot driving in the wrong direction when navigating to a target.
> esp32/PrimaryESP32: Fix inverted speed in Navigator

- README.md
- docs/wifi_ble_communication_protocol.md
To make the TCP and BLE protocol functionality the same following things were changed:
- It is now possible to remove ALL obstacles by sending 0 bytes in the RemoveObstacle characteristic
- It is now possible to configure the positioning anchors in a new added characteristic
Some small changes for layout were also made:
- Remove unnecessary spacing in tables (not visible)
- Add some spacing in tables for better readability (not visible)
- Change the order of the two tables in BLE_CHAR_REMOVE_OBSTACLE to display the shorter table first
> docs: Make TCP & BLE protocol behaviour the same

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
Because it was accidently removed, when removing the request packet 0x02 in TCP
> clientLib: Fix positioning response interpretation

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/WiFiConnectionData.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/SpeedSteerRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/CompassResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/DistanceSensorResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ErrorResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MultipleSensorResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PositioningResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/TestResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
New features:
- Added response types as enum, and a public method GetResponseType() in the interface, to get the type of the response
- Added a third constructor in WiFiConnectionData with parameters string (IP as string format) and ushort (port)
- Added a latency property in PingResponse
- Changed the order of SpeedSteerRequest constructor so it fits the order of the name
- Change SpeedSteerRequest Test, because the parameter order was changed
> clients: Add response types and small changes

- rpi/sd_image/build_in_container.sh
Change the serial port of the console to serial0 and free up ttyS1 for
other serial devices (e.g. a positioning tag) that may be connected to
the Raspberry Pi via GPIO pins 14 and 15.
> rpi/sd_image: Free up ttyS1 serial port

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/AlphabotClientLibrary.Core.Tcp.csproj
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/AlphabotClientLibrary.Core.csproj
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/AlphabotClientLibrary.Shared.csproj
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/ResponseInterpreter.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
Closes #67 
Now where the Alphabot.NET understands the protocol, some bugs in the requests occurred, these will be fixed with that.
Bugs:
- Client crashes on TcpHandlerWindows.Disconnect() Method 
- PingResponse ctor sets the Latency negative instead of positive
- TcpResponseInterpreter throws an excpetion when wrong packet id is received
- for Xamarin .NET standard 2.0 downgrade is needed
- there is a wrong variable name in AlphabotClientLibrary.Test.Tcp.Server
> clients: Fix responses

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
- docs/wifi_ble_communication_protocol.md
Remove the compass calibration setting from the settings bit field,
as the compass can already be calibrated in another way.
> docs/protocol: Remove duplicate calibration request

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AccelerometerResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AnchorDistancesResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/GyroscopeResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
- docs/wifi_ble_communication_protocol.md
Closes #64 
Adds protocol documentation, code implementation and unit test cases for 5 new sensor responses:
- Wheel speed
- Anchor distances
- Accelerometer (IMU)
- Gyroscope (IMU)
- Magnetometer (IMU)
> docs/clients: Add missing sensor responses

- emulator_rpi.py
Fix wrong GPIO memory offset when accessing a GPIO pin above 31.
> emulator_rpi: Fix wrong GPIO memory offset

- esp32/PrimaryESP32/alphabot/alphabot.ino
Fix compile error when using version 2.0.0 of the Wire library
> esp32/PrimaryESP: Fix compile error with Wire 2.0.0

- esp32/PrimaryESP32/alphabot/StepperMotor.cpp
- esp32/PrimaryESP32/alphabot/StepperMotor.h
Move the StepperMotor task to the Ultra Low Power (ULP) coprocessor of
the ESP32. This reduces the load on the main processor while still
ensuring that the steering task runs smoothly.
> esp32/PrimaryESP32: Move StepperMotor task to ULP

- esp32/PrimaryESP32/alphabot/alphabot.ino
Fix mistakenly transmiting -2048 when the value of an axis is between 0 and -1.
> esp32/PrimaryESP: Fix wrong position data

- clients/AlphabotAndroidClient/app/src/main/java/at/mg6/filip/alphabotandroidclient/ControlActivity.java
Change the order of packets when enabling positioning, so that the
anchor locations are sent before enabling the positioning toggle.
This is to prevent the positioning system from briefly operating with
obsolete anchor locations.
> clients/android: Send anchor locations before positioning toggle

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
If the start position or the target are at the top or left edge of the
map, the map dimensions may be too small. This could lead to heap
corruption later on.
> esp32/PrimaryESP: Fix Pathfinder map dimensions

- esp32/PrimaryESP32/alphabot/alphabot.ino
By increasing the I2C speed, the ESP32 has to wait less to read data
from I2C devices. This in turn leaves more time for other operations.
> esp32/PrimaryESP: Increase I2C speed to 400 kbps

- esp32/PrimaryESP32/alphabot/MotionTracker.cpp
- esp32/PrimaryESP32/alphabot/MotionTracker.h
- esp32/PrimaryESP32/alphabot/alphabot.ino
Make the MotionTracker configurable through the constructor.
> esp32/PrimaryESP: Add sensor switches to MotionTracker

- esp32/PrimaryESP32/lib/ICM20948/src/Icm20948Transport.h
Increase the maximum read/write size that is used for I2C communication
with the ICM-20948 chip. This makes the read/write processes a bit
faster.
> esp32/PrimaryESP: Increase max ICM20948 I2C transfer size

- esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
Optimize a duplicate 2D vector normalization by caching the result.
> esp32/PrimaryESP: Optimize position calculation

- esp32/PrimaryESP32/alphabot/alphabot.ino
Do not log sensor data on every single loop iteration, because it is
unnecessarily excessive. Instead, distribute the logging packets evenly,
so that they are not all sent at once.
> esp32/PrimaryESP: Reduce number of logging packets

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
- esp32/PrimaryESP32/alphabot/Pathfinder.h
Allocate the nodes buffer of the Pathfinder when instantiating the
Pathfinder. This way, the buffer does not have to be allocated and freed
repeatedly. This fixes the problem of not having a large enough
continuous block of memory on the heap.
> esp32/PrimaryESP: Preallocate nodes buffer of Pathfinder

- esp32/PrimaryESP32/alphabot/StepperMotor.cpp
Unify the way values on RTC_SLOW_MEM are addressed in the StepperMotor class.
> esp32/PrimaryESP32: Unify RTC_SLOW_MEM addressing

- clients/AlphabotAndroidClient/app/src/main/java/at/mg6/filip/alphabotandroidclient/ControlActivity.java
- clients/AlphabotAndroidClient/app/src/main/res/layout/activity_control.xml
Distinguish between forward and backward driving when displaying wheel
speeds on the wheel speed bars. Also show the mean speed of the two
wheels instead of an estimate.
> clients/android: Improve wheel speed indicators

- esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
- esp32/PrimaryESP32/alphabot/pinconfig.h
Disable the unused TX pin of the serial communication with the
positioning module.
> esp32/PrimaryESP32: Disable unused Serial2 TX pin

- esp32/PrimaryESP32/platformio.ini
Specify the platform version in platformio.ini to prevent bugs caused
by breaking changes from future versions.
> esp32/PrimaryESP: Specify platform version in platformio.ini

- clients/AlphabotAndroidClient/app/src/main/java/at/mg6/filip/alphabotandroidclient/ControlActivity.java
Fix a bug that can cause an obstacle to have incorrect coordinates and
dimensions. This can happen while an obstacle is pending and another
obstacle is received. The client mistakes the newly received obstacle
for the pending one and assigns the wrong id to the pending obstacle.
The solution is to remove the pending obstacle and add the newly
received obstacle to the list of obstacles. There is still the problem
of removing the pending obstacle by mistake, but that is better than
having a misplaced obstacle.
> clients/android: Fix a concurrency issue
