- positioning_anchor/DWM1000_ANCHOR/DW1000.cpp
- positioning_anchor/DWM1000_ANCHOR/DW1000.h
- positioning_anchor/DWM1000_ANCHOR/DW1000Device.cpp
- positioning_anchor/DWM1000_ANCHOR/DW1000Device.h
- positioning_anchor/DWM1000_ANCHOR/DW1000Mac.cpp
- positioning_anchor/DWM1000_ANCHOR/DW1000Mac.h
- positioning_anchor/DWM1000_ANCHOR/DW1000Ranging.cpp
- positioning_anchor/DWM1000_ANCHOR/DW1000Ranging.h
- positioning_anchor/DWM1000_ANCHOR/DW1000Time.cpp
- positioning_anchor/DWM1000_ANCHOR/DW1000Time.h
- positioning_tag/DWM1000_TAG/DW1000.cpp
- positioning_tag/DWM1000_TAG/DW1000.h
- positioning_tag/DWM1000_TAG/DW1000Device.cpp
- positioning_tag/DWM1000_TAG/DW1000Device.h
- positioning_tag/DWM1000_TAG/DW1000Mac.cpp
- positioning_tag/DWM1000_TAG/DW1000Mac.h
- positioning_tag/DWM1000_TAG/DW1000Ranging.cpp
- positioning_tag/DWM1000_TAG/DW1000Ranging.h
- positioning_tag/DWM1000_TAG/DW1000Time.cpp
- positioning_tag/DWM1000_TAG/DW1000Time.h
Add const keyword to function arguments that are not modified inside
that function.
> dwm1000_anchor/tag: Make read-only arguments const

- esp32/PrimaryESP32/alphabot/StepperMotor.cpp
- esp32/PrimaryESP32/alphabot/StepperMotor.h
Make member variables private and make stepperTask function part of the
StepperMotor class.
> esp32/PrimaryESP32: Refactor StepperMotor

- docs/wifi_ble_communication_protocol.md
> docs/protocol: Add timestamp to BLE_CHAR_ANCHOR_LOCATIONS

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/BleUuids.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/AddObstacleRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateSteeringRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveAllObstaclesRequest.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
Changes made:
- Implement RemoveAllObstacles request in BLE
- Implement ConfigureAnchorLocations request in BLE
- Change calibration types in BLE
- Adding timestamps in Toggle, Target Navi, Calibrate, Add Obstacle, Remove Obstacle BLE
> Adapt client library to new protocol changes

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Client/AlphabotClientLibrary.Test.Tcp.Client.csproj
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Client/Program.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/AlphabotClientLibrary.Test.Tcp.Server.csproj
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
For testing connection, sending and receiving of packages.
Should look like this:
Closes #40
> clients: Add TCP test client and test server

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Obstacle.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
- If the obstacle is removed by its id, the position is irrelevant and there is no possibility that more than one obstacle is removed
- Add better documentation in Obstacle model (constructors and properties)
> clients: Fix incorrect documentation

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
- docs/wifi_ble_communication_protocol.md
Closes #78 
Add second wheel speed in protocol, client library and unit test
> docs: Add second wheel speed

- clients/XamarinClient/AlphabotXamarinClient/MainPage.xaml.cs
> clients/xamarin: Display ErrorResponse as DisplayAlert

- clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
- clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
- docs/wifi_ble_communication_protocol.md
Send the wheel speed with a higher resolution to be able to represent
the small values on a reasonable scale.
Edit: @LecraM2003: Adapted these changes in client library
> docs/protocol: Improve the wheel speed resolution

- esp32/PrimaryESP32/alphabot/alphabot.ino
Fix incorrect format of position and compass data when logging sensors.
> esp32/PrimaryESP32: Fix position & compass logging

- clients/AlphabotAndroidClient/app/src/main/java/at/mg6/filip/alphabotandroidclient/ControlActivity.java
Fix incorrect interpretation of received position and compass data.
> clients/android: Fix sensor data interpretation

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
- esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
- esp32/PrimaryESP32/alphabot/TwoMotorDrive.cpp
Initialize class members with default values.
> esp32/PrimaryESP: Initialize members in constructors

- esp32/PrimaryESP32/alphabot/MotionTracker.cpp
- esp32/PrimaryESP32/alphabot/MotionTracker.h
- esp32/PrimaryESP32/alphabot/alphabot.ino
Linear acceleration refers to the readings of the accelerometer without
the gravitation.
> esp32/PrimaryESP: Add linear acceleration to MotionTracker

- esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
- esp32/PrimaryESP32/alphabot/PositioningSystem.h
Filter out garbage data received from the positioning module.
> esp32/PrimaryESP: Filter ranges in PositioningSystem

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
This way the rounded values will overall be closer to the original
values.
> esp32/PrimaryESP: Round properly in Pathfinder

- esp32/PrimaryESP32/alphabot/alphabot.ino
Offload pathfinding and navigation to a seperate task running on the
other core.
> esp32/PrimaryESP: Offload pathfinding to other core

- esp32/PrimaryESP32/alphabot/Navigator.cpp
- esp32/PrimaryESP32/alphabot/config.h
Prevent the Alphabot from trembling in place when navigating in some
cases. Also prevent collisions with obstacles.
> esp32/PrimaryESP: Improve Navigator

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
- esp32/PrimaryESP32/alphabot/Pathfinder.h
Half the memory usage of the Pathfinder and improve performance by about
one percent.
> esp32/PrimaryESP32: Optimize Pathfinder

- esp32/PrimaryESP32/alphabot/Pathfinder.cpp
Fix Pathfinder inefficiency of adding duplicates of untested nodes to
the list of untested nodes. Fixing this issue significantly improves
memory usage and performance.
> esp32/PrimaryESP32: Fix Pathfinder inefficiency

- esp32/PrimaryESP32/alphabot/StepperMotor.cpp
- esp32/PrimaryESP32/alphabot/StepperMotor.h
- esp32/PrimaryESP32/alphabot/alphabot.ino
Get multiple instances of StepperMotor working at the same time.
> esp32/PrimaryESP: Allow multiple instances of StepperMotor

- clients/AlphabotAndroidClient/app/src/main/java/at/mg6/filip/alphabotandroidclient/LPSView.java
Do not simply draw a circle with a line on the map to represent the
vehicle. Draw the actual vehicle instead.
> clients/android: Draw the vehicle on the map
